### ISSUE TITLE
Has anyone tried loading the flamegraph output from hatchet into https://www.speedscope.app/? 

### ISSUE THREAD

**Issue by balos1** [llnl/hatchet#37] opened 2022-05-06 17:04 UTC
I can generate a Flamegraph using Brendan Gregg's Flamegraph perl script as shown in the documentation for Hatchet. https://www.speedscope.app/ is a nice visualizer for Flamegraphs that is suppose to support the folded stacks format, but it does not recognize my file (the one that Flamegraph.pl reads fine). I was just wondering if anyone has successfully used https://www.speedscope.app/ with output from hatchet or not (in which case, maybe it is something specific to file file).

**Comment by slabasan** [comment] 2022-05-06 18:05
Hi @balos1, thanks for the pointer to speedscope, very cool! I just generated a text file with `gf.to_flamegraph()` using one of our hatchet test files, and am also running into an error loading it in the visualizer. Let me look into this a bit and see if we need to update hatchet's flamegraph output format.

**Comment by slabasan** [comment] 2022-05-20 22:03
@balos1 In your hatchet flamegraph output, can you confirm that some of the lines have a float value at the end of the line? I believe this is the cause of the unrecognized format error from speedscope. I've pushed up a fix here: https://github.com/LLNL/hatchet/pull/42. If you want to try re-outputting your file with ints instead of floats, please let me know if you are then able to read it into speedscope.

**Comment by balos1** [comment] 2022-05-21 00:39
Yeah, I can confirm that my file has floats and that turning them into ints allows speedscope to read it. Thanks!

**Comment by slabasan** [comment] 2022-05-21 03:49
Great! I'll get this merged in and close this issue, thanks again for reporting this!

**Closed as completed** 2022-05-21 03:51 UTC
